Add support for additional work in the direct container
babl-ws/babl pull request #62
Opened 2021-03-03 23:57 UTC by isolgpus

Noticed when running the server in direct mode, the additional work did not seem to be executed. This change just wires it up from the config.

2021-03-04 07:38 UTC, babl-ws requested changes
Thanks Jamie, just a couple of modifications needed.

2021-03-04 07:38 UTC, babl-ws commented on src/test/java/com/aitusoftware/babl/integration/SingleWebSocketSessionDirectSessionContainerAcceptanceTest.java
> +        int additionalWorkCount = 0;
`private` and `volatile` please

2021-03-04 07:38 UTC, babl-ws commented on src/test/java/com/aitusoftware/babl/integration/SingleWebSocketSessionDirectSessionContainerAcceptanceTest.java
> +import com.aitusoftware.babl.websocket.*;
No wildcard imports, please revert back to single imports

2021-03-04 07:38 UTC, babl-ws commented on src/main/java/com/aitusoftware/babl/websocket/SessionContainer.java
> +     *  @param application   the application that will process inbound messages
Remove leading space

2021-03-04 07:38 UTC, babl-ws commented on src/main/java/com/aitusoftware/babl/websocket/SessionContainer.java
> +     * @param additionalWork
Add param comment please

2021-03-04 19:03 UTC, isolgpus commented
Issues should be resolved I think. I'm surprised intellij was a bit aggressive with the import optimising

2021-03-04 19:58 UTC, babl-ws approved these changes

2021-03-05 07:28 UTC, babl-ws commented
@isolgpus I've just enabled CI for PRs, can you make a no-op commit to your PR to check that it's working please?

2021-03-05 11:28 UTC, merged